name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Build
        run: |
          npm install
          npm run package

      - uses: ncipollo/release-action@v1.0.0
        with:
          artifacts: "datestrings-*.vsix"
          token: ${{ secrets.GITHUB_TOKEN }}
